source "https://rubygems.org"

gem "fastlane"
gem "logger"
gem "abbrev"        # Required for highline
gem "fiddle"        # Required for registry handling
gem "mutex_m"       # Required for httpclient

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
